export const medicalPdfs = [
    {
        category_name: "Anatomy",
        web_view: false,
        sub_categories: [
            {
                sub_category: "Gross Anatomy",
                web_view: true,
                pdfs: [
                    {
                        name: "Osteology Basics",
                        description: "Detailed study of bones",
                        date: "2025-01-10",
                        size: "2.3 MB",
                        link: "/pdfs/anatomy/osteology-basics.pdf",
                        web_view: true,
                    },
                    {
                        name: "Joints Overview",
                        description: "Classification and structure of joints",
                        date: "2025-01-11",
                        size: "2.1 MB",
                        link: "/pdfs/anatomy/joints.pdf",
                        web_view: true,
                    },
                    {
                        name: "Muscle Anatomy",
                        description: "Origin, insertion, and actions of muscles",
                        date: "2025-01-12",
                        size: "3.1 MB",
                        link: "/pdfs/anatomy/muscles.pdf",
                        web_view: true,
                    },
                    {
                        name: "Blood Vessels",
                        description: "Arteries, veins, and capillaries",
                        date: "2025-01-13",
                        size: "2.5 MB",
                        link: "/pdfs/anatomy/blood-vessels.pdf",
                        web_view: false,
                    },
                    {
                        name: "Peripheral Nerves",
                        description: "Anatomy of cranial and spinal nerves",
                        date: "2025-01-14",
                        size: "2.8 MB",
                        link: "/pdfs/anatomy/nerves.pdf",
                        web_view: false,
                    },
                    {
                        name: "Thorax Anatomy",
                        description: "Heart, lungs, and mediastinum",
                        date: "2025-01-15",
                        size: "3.4 MB",
                        link: "/pdfs/anatomy/thorax.pdf",
                        web_view: true,
                    },
                    {
                        name: "Abdomen Anatomy",
                        description: "Abdominal organs and relations",
                        date: "2025-01-16",
                        size: "3.6 MB",
                        link: "/pdfs/anatomy/abdomen.pdf",
                        web_view: true,
                    },
                    {
                        name: "Pelvis & Perineum",
                        description: "Pelvic organs and perineal structures",
                        date: "2025-01-17",
                        size: "2.9 MB",
                        link: "/pdfs/anatomy/pelvis-perineum.pdf",
                        web_view: true,
                    },
                    {
                        name: "Head & Neck",
                        description: "Detailed head and neck anatomy",
                        date: "2025-01-18",
                        size: "4.2 MB",
                        link: "/pdfs/anatomy/head-neck.pdf",
                        web_view: true,
                    },
                    {
                        name: "Neuroanatomy",
                        description: "Brain and spinal cord overview",
                        date: "2025-01-19",
                        size: "4.5 MB",
                        link: "/pdfs/anatomy/neuroanatomy.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Histology",
                web_view: true,
                pdfs: [
                    {
                        name: "Cell Structure",
                        description: "Ultrastructure of the cell",
                        date: "2025-01-10",
                        size: "1.9 MB",
                        link: "/pdfs/histology/cell-structure.pdf",
                        web_view: false,
                    },
                    {
                        name: "Epithelium Tissue",
                        description: "Types and functions of epithelium",
                        date: "2025-01-11",
                        size: "1.8 MB",
                        link: "/pdfs/histology/epithelium.pdf",
                        web_view: false,
                    },
                    {
                        name: "Connective Tissue",
                        description: "Loose and dense connective tissue",
                        date: "2025-01-12",
                        size: "2.0 MB",
                        link: "/pdfs/histology/connective-tissue.pdf",
                        web_view: true,
                    },
                    {
                        name: "Muscle Tissue",
                        description: "Skeletal, cardiac, and smooth muscle",
                        date: "2025-01-13",
                        size: "2.2 MB",
                        link: "/pdfs/histology/muscle-tissue.pdf",
                        web_view: true,
                    },
                    {
                        name: "Nervous Tissue",
                        description: "Neurons and neuroglia",
                        date: "2025-01-14",
                        size: "2.1 MB",
                        link: "/pdfs/histology/nervous-tissue.pdf",
                        web_view: false,
                    },
                    {
                        name: "Organ Histology",
                        description: "Liver, kidney, lung histology",
                        date: "2025-01-15",
                        size: "2.7 MB",
                        link: "/pdfs/histology/organs.pdf",
                        web_view: false,
                    },
                ],
            },

            {
                sub_category: "Embryology",
                web_view: true,
                pdfs: [
                    {
                        name: "Gametogenesis",
                        description: "Formation of gametes",
                        date: "2025-01-10",
                        size: "1.6 MB",
                        link: "/pdfs/embryology/gametogenesis.pdf",
                        web_view: true,
                    },
                    {
                        name: "Fertilization",
                        description: "Process of fertilization",
                        date: "2025-01-11",
                        size: "1.5 MB",
                        link: "/pdfs/embryology/fertilization.pdf",
                        web_view: true,
                    },
                    {
                        name: "Gastrulation & Neurulation",
                        description: "Early embryonic development",
                        date: "2025-01-12",
                        size: "1.9 MB",
                        link: "/pdfs/embryology/gastrulation-neurulation.pdf",
                        web_view: true,
                    },
                    {
                        name: "Heart Development",
                        description: "Embryological development of heart",
                        date: "2025-01-13",
                        size: "2.0 MB",
                        link: "/pdfs/embryology/heart.pdf",
                        web_view: false,
                    },
                    {
                        name: "Congenital Anomalies",
                        description: "Common developmental anomalies",
                        date: "2025-01-14",
                        size: "2.3 MB",
                        link: "/pdfs/embryology/congenital-anomalies.pdf",
                        web_view: true,
                    },
                ],
            },
        ],
    },

    {
        category_name: "Physiology",
        web_view: false,
        sub_categories: [
            {
                sub_category: "General Physiology",
                web_view: false,
                pdfs: [
                    {
                        name: "Cell Membrane & Transport",
                        description: "Structure and transport mechanisms of cell membrane",
                        date: "2025-01-12",
                        size: "2.1 MB",
                        link: "/pdfs/physiology/cell-membrane.pdf",
                        web_view: false,
                    },
                    {
                        name: "Body Fluid Compartments",
                        description: "Distribution and regulation of body fluids",
                        date: "2025-01-12",
                        size: "1.9 MB",
                        link: "/pdfs/physiology/body-fluids.pdf",
                        web_view: false,
                    },
                    {
                        name: "Homeostasis",
                        description: "Physiological mechanisms maintaining internal balance",
                        date: "2025-01-13",
                        size: "1.7 MB",
                        link: "/pdfs/physiology/homeostasis.pdf",
                        web_view: true,
                    },
                    {
                        name: "Nerve & Muscle Physiology",
                        description: "Basics of nerve conduction and muscle contraction",
                        date: "2025-01-14",
                        size: "2.8 MB",
                        link: "/pdfs/physiology/nerve-muscle.pdf",
                        web_view: false,
                    },
                    {
                        name: "Action Potential",
                        description: "Generation and propagation of action potential",
                        date: "2025-01-14",
                        size: "2.2 MB",
                        link: "/pdfs/physiology/action-potential.pdf",
                        web_view: true,
                    },
                    {
                        name: "Receptors",
                        description: "Types and mechanisms of physiological receptors",
                        date: "2025-01-15",
                        size: "1.6 MB",
                        link: "/pdfs/physiology/receptors.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Blood",
                web_view: false,
                pdfs: [
                    {
                        name: "RBC, WBC & Platelets",
                        description: "Structure and functions of blood cells",
                        date: "2025-01-16",
                        size: "2.4 MB",
                        link: "/pdfs/physiology/blood-cells.pdf",
                        web_view: false,
                    },
                    {
                        name: "Hemoglobin",
                        description: "Structure, function, and regulation of hemoglobin",
                        date: "2025-01-16",
                        size: "1.8 MB",
                        link: "/pdfs/physiology/hemoglobin.pdf",
                        web_view: false,
                    },
                    {
                        name: "Anemia",
                        description: "Types, causes, and physiological basis of anemia",
                        date: "2025-01-17",
                        size: "2.3 MB",
                        link: "/pdfs/physiology/anemia.pdf",
                        web_view: false,
                    },
                    {
                        name: "Blood Groups",
                        description: "ABO and Rh blood group systems",
                        date: "2025-01-17",
                        size: "1.5 MB",
                        link: "/pdfs/physiology/blood-groups.pdf",
                        web_view: true,
                    },
                    {
                        name: "Hemostasis",
                        description: "Physiology of bleeding control",
                        date: "2025-01-18",
                        size: "2.0 MB",
                        link: "/pdfs/physiology/hemostasis.pdf",
                        web_view: true,
                    },
                    {
                        name: "Coagulation",
                        description: "Clotting factors and coagulation pathways",
                        date: "2025-01-18",
                        size: "2.6 MB",
                        link: "/pdfs/physiology/coagulation.pdf",
                        web_view: false,
                    },
                ],
            },

            {
                sub_category: "Cardiovascular System",
                web_view: false,
                pdfs: [
                    {
                        name: "Cardiac Cycle",
                        description: "Phases of cardiac cycle and pressure changes",
                        date: "2025-01-19",
                        size: "2.7 MB",
                        link: "/pdfs/physiology/cardiac-cycle.pdf",
                        web_view: true,
                    },
                    {
                        name: "Heart Sounds",
                        description: "Origin and clinical significance of heart sounds",
                        date: "2025-01-19",
                        size: "1.6 MB",
                        link: "/pdfs/physiology/heart-sounds.pdf",
                        web_view: true,
                    },
                    {
                        name: "ECG",
                        description: "Basics of electrocardiography interpretation",
                        date: "2025-01-20",
                        size: "2.9 MB",
                        link: "/pdfs/physiology/ecg.pdf",
                        web_view: false,
                    },
                    {
                        name: "Blood Pressure",
                        description: "Regulation and measurement of blood pressure",
                        date: "2025-01-20",
                        size: "2.2 MB",
                        link: "/pdfs/physiology/blood-pressure.pdf",
                        web_view: true,
                    },
                    {
                        name: "Regulation of Circulation",
                        description: "Neural and hormonal control of circulation",
                        date: "2025-01-21",
                        size: "2.5 MB",
                        link: "/pdfs/physiology/circulation-regulation.pdf",
                        web_view: false,
                    },
                ],
            },

            {
                sub_category: "Respiratory System",
                web_view: true,
                pdfs: [
                    {
                        name: "Lung Volumes",
                        description: "Spirometry and lung volume measurements",
                        date: "2025-01-22",
                        size: "2.1 MB",
                        link: "/pdfs/physiology/lung-volumes.pdf",
                        web_view: true,
                    },
                    {
                        name: "Gas Exchange",
                        description: "Diffusion of gases across respiratory membrane",
                        date: "2025-01-22",
                        size: "2.3 MB",
                        link: "/pdfs/physiology/gas-exchange.pdf",
                        web_view: false,
                    },
                    {
                        name: "Transport of O₂ & CO₂",
                        description: "Mechanisms of oxygen and carbon dioxide transport",
                        date: "2025-01-23",
                        size: "2.6 MB",
                        link: "/pdfs/physiology/gas-transport.pdf",
                        web_view: true,
                    },
                    {
                        name: "Regulation of Respiration",
                        description: "Neural and chemical control of breathing",
                        date: "2025-01-23",
                        size: "2.0 MB",
                        link: "/pdfs/physiology/respiration-regulation.pdf",
                        web_view: true,
                    },
                    {
                        name: "Hering–Breuer Reflex",
                        description: "Protective reflex in respiratory physiology",
                        date: "2025-01-24",
                        size: "1.4 MB",
                        link: "/pdfs/physiology/hering-breuer.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "CNS",
                web_view: false,
                pdfs: [
                    {
                        name: "Reflexes",
                        description: "Types and physiology of reflex actions",
                        date: "2025-01-25",
                        size: "1.9 MB",
                        link: "/pdfs/physiology/reflexes.pdf",
                        web_view: true,
                    },
                    {
                        name: "Sensory System",
                        description: "Physiology of sensory pathways",
                        date: "2025-01-25",
                        size: "2.4 MB",
                        link: "/pdfs/physiology/sensory-system.pdf",
                        web_view: false,
                    },
                    {
                        name: "Motor System",
                        description: "Motor pathways and voluntary movement control",
                        date: "2025-01-26",
                        size: "2.7 MB",
                        link: "/pdfs/physiology/motor-system.pdf",
                        web_view: false,
                    },
                    {
                        name: "Basal Ganglia & Cerebellum",
                        description: "Role in movement coordination",
                        date: "2025-01-26",
                        size: "2.8 MB",
                        link: "/pdfs/physiology/basal-ganglia.pdf",
                        web_view: false,
                    },
                    {
                        name: "Sleep & EEG",
                        description: "Stages of sleep and EEG patterns",
                        date: "2025-01-27",
                        size: "2.2 MB",
                        link: "/pdfs/physiology/sleep-eeg.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Renal Physiology",
                web_view: true,
                pdfs: [
                    {
                        name: "Nephron",
                        description: "Structure and function of nephron",
                        date: "2025-01-28",
                        size: "2.1 MB",
                        link: "/pdfs/physiology/nephron.pdf",
                        web_view: false,
                    },
                    {
                        name: "GFR",
                        description: "Glomerular filtration rate and regulation",
                        date: "2025-01-28",
                        size: "1.8 MB",
                        link: "/pdfs/physiology/gfr.pdf",
                        web_view: true,
                    },
                    {
                        name: "Tubular Reabsorption",
                        description: "Mechanisms of tubular transport",
                        date: "2025-01-29",
                        size: "2.3 MB",
                        link: "/pdfs/physiology/tubular-reabsorption.pdf",
                        web_view: false,
                    },
                    {
                        name: "Acid–Base Balance",
                        description: "Renal regulation of acid-base status",
                        date: "2025-01-29",
                        size: "2.0 MB",
                        link: "/pdfs/physiology/acid-base.pdf",
                        web_view: false,
                    },
                    {
                        name: "Micturition",
                        description: "Physiology of urine storage and voiding",
                        date: "2025-01-30",
                        size: "1.5 MB",
                        link: "/pdfs/physiology/micturition.pdf",
                        web_view: false,
                    },
                ],
            },

            {
                sub_category: "Gastrointestinal Physiology",
                web_view: false,
                pdfs: [
                    {
                        name: "Saliva",
                        description: "Composition and functions of saliva",
                        date: "2025-01-31",
                        size: "1.4 MB",
                        link: "/pdfs/physiology/saliva.pdf",
                        web_view: false,
                    },
                    {
                        name: "Gastric Secretion",
                        description: "Mechanism and regulation of gastric juice",
                        date: "2025-01-31",
                        size: "2.2 MB",
                        link: "/pdfs/physiology/gastric-secretion.pdf",
                        web_view: true,
                    },
                    {
                        name: "Pancreatic Juice & Bile",
                        description: "Digestive secretions of pancreas and liver",
                        date: "2025-02-01",
                        size: "2.5 MB",
                        link: "/pdfs/physiology/pancreatic-bile.pdf",
                        web_view: false,
                    },
                    {
                        name: "Digestion & Absorption",
                        description: "Process of nutrient digestion and absorption",
                        date: "2025-02-01",
                        size: "2.7 MB",
                        link: "/pdfs/physiology/digestion-absorption.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Endocrine",
                web_view: true,
                pdfs: [
                    {
                        name: "Hypothalamus–Pituitary Axis",
                        description: "Central control of endocrine system",
                        date: "2025-02-02",
                        size: "2.6 MB",
                        link: "/pdfs/physiology/hypothalamus-pituitary.pdf",
                        web_view: true,
                    },
                    {
                        name: "Thyroid & Parathyroid",
                        description: "Hormones and physiological functions",
                        date: "2025-02-02",
                        size: "2.1 MB",
                        link: "/pdfs/physiology/thyroid-parathyroid.pdf",
                        web_view: false,
                    },
                    {
                        name: "Adrenal Gland",
                        description: "Cortex and medulla hormone physiology",
                        date: "2025-02-03",
                        size: "2.3 MB",
                        link: "/pdfs/physiology/adrenal.pdf",
                        web_view: false,
                    },
                    {
                        name: "Pancreas & Growth Hormone",
                        description: "Endocrine pancreas and growth hormone",
                        date: "2025-02-03",
                        size: "2.0 MB",
                        link: "/pdfs/physiology/pancreas-gh.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Reproductive Physiology",
                web_view: true,
                pdfs: [
                    {
                        name: "Male Reproduction",
                        description: "Physiology of male reproductive system",
                        date: "2025-02-04",
                        size: "2.2 MB",
                        link: "/pdfs/physiology/male-reproduction.pdf",
                        web_view: true,
                    },
                    {
                        name: "Female Menstrual Cycle",
                        description: "Hormonal regulation of menstrual cycle",
                        date: "2025-02-04",
                        size: "2.5 MB",
                        link: "/pdfs/physiology/menstrual-cycle.pdf",
                        web_view: false,
                    },
                    {
                        name: "Pregnancy & Lactation",
                        description: "Physiology of pregnancy and milk production",
                        date: "2025-02-05",
                        size: "2.8 MB",
                        link: "/pdfs/physiology/pregnancy-lactation.pdf",
                        web_view: true,
                    },
                    {
                        name: "Contraception",
                        description: "Physiological basis of contraceptive methods",
                        date: "2025-02-05",
                        size: "1.6 MB",
                        link: "/pdfs/physiology/contraception.pdf",
                        web_view: true,
                    },
                ],
            },
        ],
    },
    {
        category_name: "Biochemistry",
        web_view: true,
        sub_categories: [
            {
                sub_category: "General Biochemistry",
                web_view: true,
                pdfs: [
                    {
                        name: "Cell Structure",
                        description: "Biochemical organization of the cell",
                        date: "2025-01-10",
                        size: "2.0 MB",
                        link: "/pdfs/biochemistry/cell-structure.pdf",
                        web_view: false,
                    },
                    {
                        name: "Biomolecules",
                        description: "Carbohydrates, lipids, proteins and nucleic acids",
                        date: "2025-01-11",
                        size: "2.4 MB",
                        link: "/pdfs/biochemistry/biomolecules.pdf",
                        web_view: true,
                    },
                    {
                        name: "Enzymes",
                        description: "Enzyme kinetics, inhibition and regulation",
                        date: "2025-01-12",
                        size: "2.6 MB",
                        link: "/pdfs/biochemistry/enzymes.pdf",
                        web_view: true,
                    },
                    {
                        name: "Acid–Base Balance",
                        description: "Regulation of pH in the human body",
                        date: "2025-01-13",
                        size: "2.1 MB",
                        link: "/pdfs/biochemistry/acid-base-balance.pdf",
                        web_view: true,
                    },
                    {
                        name: "Buffers",
                        description: "Physiological buffer systems",
                        date: "2025-01-14",
                        size: "1.9 MB",
                        link: "/pdfs/biochemistry/buffers.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Carbohydrate Metabolism",
                web_view: true,
                pdfs: [
                    {
                        name: "Glycolysis",
                        description: "Steps, regulation and clinical importance",
                        date: "2025-01-15",
                        size: "2.8 MB",
                        link: "/pdfs/biochemistry/glycolysis.pdf",
                        web_view: true,
                    },
                    {
                        name: "TCA Cycle",
                        description: "Krebs cycle reactions and energy yield",
                        date: "2025-01-16",
                        size: "2.5 MB",
                        link: "/pdfs/biochemistry/tca-cycle.pdf",
                        web_view: false,
                    },
                    {
                        name: "Gluconeogenesis",
                        description: "Formation of glucose from non-carbohydrates",
                        date: "2025-01-17",
                        size: "2.3 MB",
                        link: "/pdfs/biochemistry/gluconeogenesis.pdf",
                        web_view: true,
                    },
                    {
                        name: "Glycogen Metabolism",
                        description: "Glycogenesis and glycogenolysis",
                        date: "2025-01-18",
                        size: "2.6 MB",
                        link: "/pdfs/biochemistry/glycogen-metabolism.pdf",
                        web_view: false,
                    },
                    {
                        name: "HMP Shunt",
                        description: "Hexose monophosphate pathway",
                        date: "2025-01-19",
                        size: "2.2 MB",
                        link: "/pdfs/biochemistry/hmp-shunt.pdf",
                        web_view: false,
                    },
                ],
            },

            {
                sub_category: "Lipid Metabolism",
                web_view: true,
                pdfs: [
                    {
                        name: "Fatty Acid Oxidation",
                        description: "Beta oxidation of fatty acids",
                        date: "2025-01-20",
                        size: "2.7 MB",
                        link: "/pdfs/biochemistry/fatty-acid-oxidation.pdf",
                        web_view: false,
                    },
                    {
                        name: "Lipogenesis",
                        description: "Synthesis of fatty acids",
                        date: "2025-01-21",
                        size: "2.4 MB",
                        link: "/pdfs/biochemistry/lipogenesis.pdf",
                        web_view: false,
                    },
                    {
                        name: "Cholesterol Metabolism",
                        description: "Cholesterol synthesis and regulation",
                        date: "2025-01-22",
                        size: "2.6 MB",
                        link: "/pdfs/biochemistry/cholesterol-metabolism.pdf",
                        web_view: true,
                    },
                    {
                        name: "Lipoproteins",
                        description: "Types and functions of lipoproteins",
                        date: "2025-01-23",
                        size: "2.5 MB",
                        link: "/pdfs/biochemistry/lipoproteins.pdf",
                        web_view: true,
                    },
                    {
                        name: "Ketone Bodies",
                        description: "Ketogenesis and utilization",
                        date: "2025-01-24",
                        size: "2.1 MB",
                        link: "/pdfs/biochemistry/ketone-bodies.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Protein & Amino Acid Metabolism",
                web_view: false,
                pdfs: [
                    {
                        name: "Transamination",
                        description: "Transfer of amino groups",
                        date: "2025-01-25",
                        size: "2.2 MB",
                        link: "/pdfs/biochemistry/transamination.pdf",
                        web_view: true,
                    },
                    {
                        name: "Deamination",
                        description: "Removal of amino groups",
                        date: "2025-01-26",
                        size: "2.0 MB",
                        link: "/pdfs/biochemistry/deamination.pdf",
                        web_view: false,
                    },
                    {
                        name: "Urea Cycle",
                        description: "Detoxification of ammonia",
                        date: "2025-01-27",
                        size: "2.6 MB",
                        link: "/pdfs/biochemistry/urea-cycle.pdf",
                        web_view: true,
                    },
                    {
                        name: "Inborn Errors of Metabolism",
                        description: "Genetic metabolic disorders",
                        date: "2025-01-28",
                        size: "2.9 MB",
                        link: "/pdfs/biochemistry/inborn-errors.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Molecular Biology",
                web_view: true,
                pdfs: [
                    {
                        name: "DNA Replication",
                        description: "Mechanism of DNA replication",
                        date: "2025-01-29",
                        size: "2.3 MB",
                        link: "/pdfs/biochemistry/dna-replication.pdf",
                        web_view: false,
                    },
                    {
                        name: "Transcription",
                        description: "RNA synthesis from DNA",
                        date: "2025-01-30",
                        size: "2.1 MB",
                        link: "/pdfs/biochemistry/transcription.pdf",
                        web_view: true,
                    },
                    {
                        name: "Translation",
                        description: "Protein synthesis process",
                        date: "2025-01-31",
                        size: "2.4 MB",
                        link: "/pdfs/biochemistry/translation.pdf",
                        web_view: false,
                    },
                    {
                        name: "Gene Regulation",
                        description: "Control of gene expression",
                        date: "2025-02-01",
                        size: "2.2 MB",
                        link: "/pdfs/biochemistry/gene-regulation.pdf",
                        web_view: false,
                    },
                ],
            },

            {
                sub_category: "Vitamins & Minerals",
                web_view: false,
                pdfs: [
                    {
                        name: "Fat-Soluble Vitamins",
                        description: "Vitamins A, D, E and K",
                        date: "2025-02-02",
                        size: "2.5 MB",
                        link: "/pdfs/biochemistry/fat-soluble-vitamins.pdf",
                        web_view: true,
                    },
                    {
                        name: "Water-Soluble Vitamins",
                        description: "B-complex vitamins and Vitamin C",
                        date: "2025-02-03",
                        size: "2.4 MB",
                        link: "/pdfs/biochemistry/water-soluble-vitamins.pdf",
                        web_view: false,
                    },
                    {
                        name: "Minerals",
                        description: "Calcium, iron, iodine and trace elements",
                        date: "2025-02-04",
                        size: "2.3 MB",
                        link: "/pdfs/biochemistry/minerals.pdf",
                        web_view: true,
                    },
                ],
            },

            {
                sub_category: "Clinical Biochemistry",
                web_view: true,
                pdfs: [
                    {
                        name: "Liver Function Tests (LFT)",
                        description: "Interpretation of liver enzymes",
                        date: "2025-02-05",
                        size: "2.6 MB",
                        link: "/pdfs/biochemistry/lft.pdf",
                        web_view: false,
                    },
                    {
                        name: "Renal Function Tests (RFT)",
                        description: "Assessment of kidney function",
                        date: "2025-02-06",
                        size: "2.5 MB",
                        link: "/pdfs/biochemistry/rft.pdf",
                        web_view: false,
                    },
                    {
                        name: "Blood Glucose",
                        description: "Regulation and disorders of glucose",
                        date: "2025-02-07",
                        size: "2.3 MB",
                        link: "/pdfs/biochemistry/blood-glucose.pdf",
                        web_view: false,
                    },
                    {
                        name: "Lipid Profile",
                        description: "Cholesterol and triglyceride analysis",
                        date: "2025-02-08",
                        size: "2.4 MB",
                        link: "/pdfs/biochemistry/lipid-profile.pdf",
                        web_view: true,
                    },
                    {
                        name: "Acid–Base Disorders",
                        description: "Metabolic and respiratory imbalances",
                        date: "2025-02-09",
                        size: "2.6 MB",
                        link: "/pdfs/biochemistry/acid-base-disorders.pdf",
                        web_view: true,
                    },

                ],
            },
        ],
    }

];